[package]
name = "simulation"
version = "0.1.0"
authors = ["technolapin <technolapin@orange.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium="0.29.0"
nalgebra="*"
rayon="*"
rand = "*"